// Stroke Sight — Translations: es
if (!window.STRINGS) window.STRINGS = {};
STRINGS['es'] = {
  "tagline": "Entrenamiento del campo visual",
  "subtitle": "Ejercicios diarios diseñados para la recuperación de la hemianopía tras un ictus. Sesiones cortas, práctica constante.",
  "notice_title": "Herramienta de apoyo al bienestar — no es un dispositivo médico.",
  "notice_body": "Stroke Sight está diseñada para apoyar su práctica diaria junto con la atención profesional. No diagnostica, trata ni cura ninguna condición médica. Siga siempre las indicaciones de su neuro-oftalmólogo, equipo de rehabilitación de ictus u otro profesional clínico cualificado.",
  "side_question": "¿Qué lado está afectado?",
  "side_left": "Lado izquierdo",
  "side_right": "Lado derecho",
  "choose_exercise": "ELIGE UN EJERCICIO",
  "nav_exercises": "Ejercicios",
  "nav_progress": "Progreso",
  "nav_about": "Acerca de",
  "ex_anchor_name": "Anclaje y exploración",
  "ex_anchor_badge": "Base",
  "ex_reading_name": "Exploración de línea de lectura",
  "ex_reading_badge": "Lectura",
  "ex_flicker_name": "Parpadeo periférico",
  "ex_flicker_badge": "Conciencia",
  "ex_grid_name": "Cuadrícula de búsqueda visual",
  "ex_grid_badge": "Exploración",
  "ex_anchor_desc": "Mantenga la mirada en la cruz de fijación central. Mueva los ojos rápidamente para tocar los objetivos verdes — el 70% aparece en su lado afectado para entrenar las sacadas hacia el campo ciego.",
  "ex_reading_desc": "Reconstruya el hábito de lectura mediante el anclaje y la exploración. Comience en el punto rojo y luego explore para encontrar y tocar la palabra objetivo en negrita.",
  "ex_flicker_desc": "Detecte parpadeos amarillos sutiles en cualquier parte de la pantalla sin apartar los ojos de la cruz central. Baja exigencia, gran beneficio para la conciencia visual.",
  "ex_grid_desc_ltr": "Encuentre la estrella objetivo oculta entre símbolos en una cuadrícula completa. Explore de izquierda a derecha, fila por fila — simula tareas de exploración de la vida real.",
  "ex_grid_desc_rtl": "Encuentre la estrella objetivo oculta entre símbolos en una cuadrícula completa. Explore de derecha a izquierda, fila por fila — simula tareas de exploración de la vida real.",
  "ex_anchor_instr": "Mantenga los ojos en la cruz blanca hasta que aparezca un punto verde. Luego mueva la mirada rápidamente y tóquelo. No se mueva antes de que aparezca el punto.",
  "ex_reading_instr_left": "Primero encuentre el punto de anclaje rojo en el borde izquierdo. Luego explore hacia la derecha para tocar la palabra blanca en negrita. Reentrena el patrón de lectura.",
  "ex_reading_instr_right": "Primero encuentre el punto de anclaje rojo en el borde derecho. Luego explore hacia la izquierda para tocar la palabra blanca en negrita. Reentrena el patrón de lectura.",
  "ex_flicker_instr": "Mire fijamente la cruz central — no mueva los ojos. Cuando perciba algún parpadeo amarillo, pulse Espacio o toque la pantalla inmediatamente.",
  "ex_grid_instr_ltr": "Encuentre la estrella ★ oculta entre los símbolos. Explore de izquierda a derecha, fila por fila. Tóquela en el momento en que la encuentre.",
  "ex_grid_instr_rtl": "Encuentre la estrella ★ oculta entre los símbolos. Explore de derecha a izquierda, fila por fila. Tóquela en el momento en que la encuentre.",
  "start_prompt": "Toque en cualquier lugar para comenzar",
  "session_complete": "Sesión completada",
  "score_label": "Puntuación",
  "hits_label": "Aciertos",
  "accuracy_label": "Precisión",
  "avg_reaction": "Reacción media",
  "btn_done": "Hecho",
  "time_label": "Tiempo",
  "canvas_affected_left": "← Campo afectado",
  "canvas_sighted_right": "Campo visual →",
  "canvas_sighted_left": "← Campo visual",
  "canvas_affected_right": "Campo afectado →",
  "canvas_start_right": "Empieza aquí →",
  "canvas_start_left": "← Empieza aquí",
  "canvas_scan_right": "Explora → toca la palabra en negrita",
  "canvas_scan_left": "Toca la palabra en negrita ← explora",
  "canvas_reading_prompt_right": "Empieza en el punto de anclaje rojo, luego explora a la derecha",
  "canvas_reading_prompt_left": "Empieza en el punto de anclaje rojo, luego explora a la izquierda",
  "canvas_grid_instr_ltr": "Encuentra la ★ estrella — explora de izq. a der., fila por fila",
  "canvas_grid_instr_rtl": "Encuentra la ★ estrella — explora de der. a izq., fila por fila",
  "canvas_grid_prompt_ltr": "Explora la cuadrícula de izq. a der., fila por fila — halla la ★",
  "canvas_grid_prompt_rtl": "Explora la cuadrícula de der. a izq., fila por fila — halla la ★",
  "progress_title": "Tu progreso",
  "total_sessions": "SESIONES TOTALES",
  "minutes_practised": "MINUTOS PRACTICADOS",
  "avg_score": "PUNTUACIÓN MEDIA",
  "avg_reaction_time": "REACCIÓN MEDIA",
  "recent_sessions": "SESIONES RECIENTES",
  "no_sessions_yet": "Aún no hay sesiones. Completa un ejercicio para seguir tu progreso aquí.",
  "sessions_count": "SESIONES",
  "no_sessions_exercise": "Aún no hay sesiones para este ejercicio.",
  "bench_guide": "Guía para adultos sanos — no es un objetivo clínico",
  "improvement_label": "Primeras 3 → Últimas 3",
  "score_up": "puntuación",
  "reaction_up": "reacción",
  "best_score": "Mejor",
  "avg_score_short": "Media",
  "btn_clear_data": "Borrar todos los datos",
  "confirm_clear": "¿Eliminar todos tus datos de progreso? Esta acción no se puede deshacer.",
  "email_section_title": "Enviar mi progreso por correo",
  "email_placeholder": "tu@correo.com",
  "btn_send_report": "Enviar informe",
  "email_hint": "Abre tu aplicación de correo con un resumen de progreso precompletado. Puedes editarlo antes de enviar.",
  "report_header": "Stroke Sight – Entrenador de campo visual",
  "report_affected_side": "Lado afectado",
  "report_overview": "── RESUMEN ──",
  "report_by_exercise": "── POR EJERCICIO ──",
  "report_total_sessions": "Sesiones totales",
  "report_minutes": "Minutos practicados",
  "report_avg_score": "Puntuación media general",
  "report_avg_rt": "Tiempo de reacción medio general",
  "report_improvement": "Mejora (primeras 3 → últimas 3): puntuación",
  "report_footer1": "Enviado desde Stroke Sight – Entrenador de campo visual",
  "report_footer2": "strokesight.app",
  "report_footer3": "Estos resultados son solo para seguimiento personal. Stroke Sight es una herramienta de apoyo al bienestar — no es un dispositivo médico. Los resultados no son una evaluación clínica.",
  "no_sessions_report": "Completa al menos una sesión de ejercicio primero.",
  "email_required": "Por favor, introduce una dirección de correo electrónico.",
  "about_title": "Acerca de Stroke Sight",
  "about_app_heading": "Sobre esta aplicación",
  "about_app_body": "Stroke Sight es una aplicación de apoyo al bienestar para personas que viven con hemianopía — pérdida parcial de la visión causada habitualmente por un ictus. No es un dispositivo médico y no sustituye la rehabilitación profesional. Úsela junto con las indicaciones de su neuro-oftalmólogo o equipo de rehabilitación de ictus.",
  "about_why_heading": "¿Por qué estos cuatro ejercicios?",
  "about_why_body": "Tras un ictus que causa hemianopía, el cerebro pierde la exploración automática hacia el campo afectado. Estos ejercicios se basan en el entrenamiento sacádico compensatorio — enseñando movimientos oculares deliberados para compensar el campo ausente.",
  "about_exercises_heading": "Los ejercicios",
  "about_how_heading": "Cómo usar esta aplicación",
  "about_how_1": "Intente practicar entre 5 y 15 minutos al día; poco y frecuente es mejor que sesiones largas e irregulares.",
  "about_how_2": "Empiece con Parpadeo periférico si el nivel de fatiga es alto.",
  "about_how_3": "Muestre la pestaña de Progreso a su terapeuta en las citas.",
  "about_how_4": "Esta aplicación funciona completamente sin conexión — no necesita internet después del primer guardado.",
  "about_important_heading": "Importante",
  "about_important_body": "Esta aplicación complementa la rehabilitación profesional, no la sustituye. La recuperación de la pérdida de campo visual relacionada con un ictus varía considerablemente entre individuos. Siga siempre las indicaciones de su equipo clínico.",
  "btn_privacy": "Política de privacidad",
  "privacy_title": "Política de privacidad",
  "privacy_short_heading": "La versión breve",
  "privacy_short_body": "Stroke Sight no recopila ningún dato personal en absoluto. Todo lo que hace la aplicación ocurre íntegramente en su dispositivo. Sin cuentas, sin seguimiento, sin análisis, sin internet.",
  "lang_label": "Idioma",
  "about_evidence_basis": "Los ejercicios para hemianopsia (Anchor & Scan, Reading Line Scan, Peripheral Flicker, Visual Search Grid) se basan en el entrenamiento compensatorio de exploración sacádica, enfoque respaldado por la guía NICE NG236 y más de 40 años de investigación de Zihl, Kerkhoff, Pambakian y Trauzettel-Klosinski. Los ejercicios para heminegligencia visuoespacial (Smooth Pursuit, calibración de Line Bisection) siguen la tradición del entrenamiento de movimientos de seguimiento ocular suave recomendada por las directrices de la Sociedad Neurológica Alemana y con la máxima calificación de evidencia en la revisión sistemática de Klinke et al. (2015). Las señales auditivas espaciales se basan en la investigación de estimulación multisensorial de Bolognini y Tinelli. Los ejercicios para escotoma (Blind Spot Tracker, Gap Fill) ofrecen entrenamiento de conciencia y práctica de completado perceptivo alrededor del punto ciego. Esto complementa —pero no reemplaza— el entrenamiento de visión excéntrica y el locus retiniano preferente que ofrecen los especialistas en baja visión.",
  "bisection_neglect_complete_left": "Sesión completada. Si tendió a tocar a la derecha del centro, eso es el sesgo típico de negligencia. La conciencia de su lado izquierdo mejorará con práctica constante.",
  "bisection_neglect_complete_right": "Sesión completada. Si tendió a tocar a la derecha del centro, eso es el sesgo típico de negligencia. La conciencia de su lado derecho mejorará con práctica constante.",
  "cond_hemianopia": "Hemianopsia",
  "cond_hemianopia_desc": "Pérdida de la mitad de su campo visual",
  "cond_neglect": "Heminegligencia Visuoespacial",
  "cond_neglect_desc": "Su cerebro no percibe un lado",
  "cond_pick_quadrant": "¿Qué cuadrante está afectado?",
  "cond_pick_scotoma": "Toque su área aproximada de punto ciego",
  "cond_pick_side": "¿Qué lado está afectado?",
  "cond_quadrantanopia": "Cuadrantanopsia",
  "cond_quadrantanopia_desc": "Pérdida de un cuadrante de su campo visual",
  "cond_scotoma": "Escotoma",
  "cond_scotoma_desc": "Un punto ciego en su visión — entrenamiento de conciencia",
  "cond_title": "¿Cuál es su afección visual?",
  "ex_bisection_badge": "Calibrar",
  "ex_bisection_desc": "Biseccione líneas para medir su sesgo espacial. Su desviación calibra la dificultad del ejercicio de Exploración de Atención que sigue.",
  "ex_bisection_instr": "Toque donde crea que está el centro exacto de cada línea. Su desviación promedio ajustará la ayuda que recibirá en el siguiente ejercicio.",
  "ex_bisection_name": "Line Bisection",
  "ex_gapfill_badge": "Escotoma",
  "ex_gapfill_desc": "Los objetivos forman un patrón con huecos en su área de punto ciego. Toque donde deberían estar los objetivos faltantes. Práctica de completado perceptivo — ejercitando la capacidad de su cerebro para interpretar información visual incompleta.",
  "ex_gapfill_instr": "Observe el anillo de objetivos. Algunos faltan porque caen en su punto ciego. Toque donde crea que deberían estar los que faltan.",
  "ex_gapfill_name": "Gap Fill",
  "ex_pursuit_badge": "Negligencia",
  "ex_pursuit_desc": "Siga un objetivo en movimiento mientras cruza hacia su lado de negligencia. Entrenamiento de movimientos de seguimiento ocular suave — el enfoque con mayor evidencia para la recuperación de la heminegligencia visuoespacial.",
  "ex_pursuit_instr": "Un círculo se mueve lentamente por la pantalla hacia su lado de negligencia. Sígalo con sus ojos. Cuando se detenga, tóquelo para confirmar que lo rastreó.",
  "ex_pursuit_name": "Smooth Pursuit",
  "ex_tracker_badge": "Escotoma",
  "ex_tracker_desc": "Rastree un objetivo en movimiento mientras cruza su área de punto ciego. Es un entrenamiento de conciencia — desarrollando la capacidad de su cerebro para predecir y compensar alrededor del escotoma, en lugar de visión excéntrica o desarrollo del locus retiniano preferente.",
  "ex_tracker_instr": "Observe el punto verde moverse por la pantalla. Cuando desaparezca en su punto ciego, toque donde crea que está ahora.",
  "ex_tracker_name": "Blind Spot Tracker",
  "progress_neglect_note": "Consejo de recuperación de negligencia: pida a alguien que observe qué lado de la pantalla tiende a no ver. La mejora a menudo se manifiesta como menos objetivos perdidos en su lado de negligencia tras semanas de práctica.",
  "pursuit_neglect_complete_left": "Sesión completada. Si algunos objetivos de su lado izquierdo fueron difíciles de notar, eso es normal en la recuperación de negligencia. La práctica constante ayuda.",
  "pursuit_neglect_complete_right": "Sesión completada. Si algunos objetivos de su lado derecho fueron difíciles de notar, eso es normal en la recuperación de negligencia. La práctica constante ayuda.",
  "quad_LL": "Inferior izquierdo",
  "quad_LR": "Inferior derecho",
  "quad_UL": "Superior izquierdo",
  "quad_UR": "Superior derecho",
  "safety_warning": "Detenga y consulte a su médico si experimenta mayor dolor de cabeza, mareos, náuseas o síntomas visuales durante o después de los ejercicios.",
  "settings_sound_hint": "Señales de audio estéreo durante los ejercicios. Sutil utiliza tonos suaves; Prominente utiliza tonos más fuertes. Desactive si los sonidos son incómodos o desorientadores.",
  "settings_sound_label": "Señales de sonido",
  "settings_sound_off": "Desactivado",
  "settings_sound_prominent": "Prominente",
  "settings_sound_subtle": "Sutil"
};

if (!window.WORD_LISTS) window.WORD_LISTS = {};
WORD_LISTS['es'] = [
  "que",
  "con",
  "los",
  "del",
  "una",
  "por",
  "las",
  "son",
  "hay",
  "ver",
  "dar",
  "dos",
  "fin",
  "luz",
  "mar",
  "pan",
  "pie",
  "red",
  "sal",
  "sol",
  "sur",
  "voz",
  "agua",
  "amor",
  "bien",
  "boca",
  "cara",
  "casa",
  "casi",
  "dato",
  "deja",
  "ella",
  "esto",
  "gray",
  "hace",
  "lado",
  "leer",
  "leño",
  "mano",
  "mesa",
  "modo",
  "mundo",
  "nada",
  "niño",
  "nombre",
  "obra",
  "otra",
  "país",
  "para",
  "paso",
  "pelo",
  "poco",
  "pero",
  "puerta",
  "ropa",
  "sabe",
  "sala",
  "sola",
  "todo",
  "tres",
  "vida",
  "zona"
];
