// Stroke Sight — Translations: fr
if (!window.STRINGS) window.STRINGS = {};
STRINGS['fr'] = {
  "tagline": "Entraînement du champ visuel",
  "subtitle": "Exercices quotidiens conçus pour la récupération de l'hémianopsie après un AVC. Séances courtes, pratique régulière.",
  "notice_title": "Outil de soutien au bien-être — pas un dispositif médical.",
  "notice_body": "Stroke Sight est conçu pour soutenir votre pratique quotidienne en complément des soins professionnels. Il ne diagnostique, ne traite ni ne guérit aucune condition médicale. Suivez toujours les recommandations de votre neuro-ophtalmologiste, de votre équipe de rééducation post-AVC ou de tout autre clinicien qualifié.",
  "side_question": "Quel côté est atteint ?",
  "side_left": "Côté gauche",
  "side_right": "Côté droit",
  "choose_exercise": "CHOISISSEZ UN EXERCICE",
  "nav_exercises": "Exercices",
  "nav_progress": "Progrès",
  "nav_about": "À propos",
  "ex_anchor_name": "Ancrage & Exploration",
  "ex_anchor_badge": "Base",
  "ex_reading_name": "Exploration de ligne de lecture",
  "ex_reading_badge": "Lecture",
  "ex_flicker_name": "Scintillement périphérique",
  "ex_flicker_badge": "Conscience",
  "ex_grid_name": "Grille de recherche visuelle",
  "ex_grid_badge": "Exploration",
  "ex_anchor_desc": "Maintenez le regard sur la croix de fixation centrale. Déplacez rapidement les yeux pour toucher les cibles vertes — 70 % apparaissent du côté atteint afin d'entraîner les saccades vers le champ aveugle.",
  "ex_reading_desc": "Rétablissez l'habitude de lecture par ancrage et exploration. Commencez au point rouge, puis explorez pour trouver et toucher le mot cible en gras.",
  "ex_flicker_desc": "Détectez de subtils scintillements jaunes n'importe où sur l'écran sans quitter la croix centrale des yeux. Faible effort, grand bénéfice pour la conscience visuelle.",
  "ex_grid_desc_ltr": "Trouvez l'étoile cible cachée parmi des symboles dans une grille complète. Explorez de gauche à droite, ligne par ligne — simule des tâches d'exploration de la vie quotidienne.",
  "ex_grid_desc_rtl": "Trouvez l'étoile cible cachée parmi des symboles dans une grille complète. Explorez de droite à gauche, ligne par ligne — simule des tâches d'exploration de la vie quotidienne.",
  "ex_anchor_instr": "Gardez les yeux sur la croix blanche jusqu'à ce qu'un point vert apparaisse. Déplacez alors rapidement le regard et touchez-le. Ne bougez pas avant l'apparition du point.",
  "ex_reading_instr_left": "Trouvez d'abord le point d'ancrage rouge sur le bord gauche. Explorez ensuite vers la droite pour toucher le mot blanc en gras. Réentraîne le schéma de lecture.",
  "ex_reading_instr_right": "Trouvez d'abord le point d'ancrage rouge sur le bord droit. Explorez ensuite vers la gauche pour toucher le mot blanc en gras. Réentraîne le schéma de lecture.",
  "ex_flicker_instr": "Fixez la croix centrale — ne bougez pas les yeux. Dès que vous percevez un scintillement jaune, appuyez sur Espace ou touchez l'écran immédiatement.",
  "ex_grid_instr_ltr": "Trouvez l'étoile ★ cachée parmi les symboles. Explorez de gauche à droite, ligne par ligne. Touchez-la dès que vous la trouvez.",
  "ex_grid_instr_rtl": "Trouvez l'étoile ★ cachée parmi les symboles. Explorez de droite à gauche, ligne par ligne. Touchez-la dès que vous la trouvez.",
  "start_prompt": "Touchez n'importe où pour commencer",
  "session_complete": "Séance terminée",
  "score_label": "Score",
  "hits_label": "Réussites",
  "accuracy_label": "Précision",
  "avg_reaction": "Réaction moy.",
  "btn_done": "Terminé",
  "time_label": "Temps",
  "canvas_affected_left": "← Champ atteint",
  "canvas_sighted_right": "Champ sain →",
  "canvas_sighted_left": "← Champ sain",
  "canvas_affected_right": "Champ atteint →",
  "canvas_start_right": "Commencez ici →",
  "canvas_start_left": "← Commencez ici",
  "canvas_scan_right": "Explorez → touchez le mot en gras",
  "canvas_scan_left": "Touchez le mot en gras ← explorez",
  "canvas_reading_prompt_right": "Partez du point d'ancrage rouge, puis explorez vers la droite",
  "canvas_reading_prompt_left": "Partez du point d'ancrage rouge, puis explorez vers la gauche",
  "canvas_grid_instr_ltr": "Trouvez l'★ étoile — de gauche à droite, ligne par ligne",
  "canvas_grid_instr_rtl": "Trouvez l'★ étoile — de droite à gauche, ligne par ligne",
  "canvas_grid_prompt_ltr": "Explorez la grille de g. à dr., ligne par ligne — trouvez l'★",
  "canvas_grid_prompt_rtl": "Explorez la grille de dr. à g., ligne par ligne — trouvez l'★",
  "progress_title": "Votre progression",
  "total_sessions": "SÉANCES TOTALES",
  "minutes_practised": "MINUTES PRATIQUÉES",
  "avg_score": "SCORE MOYEN",
  "avg_reaction_time": "RÉACTION MOY.",
  "recent_sessions": "SÉANCES RÉCENTES",
  "no_sessions_yet": "Pas encore de séances. Terminez un exercice pour suivre votre progression ici.",
  "sessions_count": "SÉANCES",
  "no_sessions_exercise": "Pas encore de séances pour cet exercice.",
  "bench_guide": "Repère pour adulte sain — pas un objectif clinique",
  "improvement_label": "3 premières → 3 dernières",
  "score_up": "score",
  "reaction_up": "réaction",
  "best_score": "Meilleur",
  "avg_score_short": "Moy.",
  "btn_clear_data": "Effacer toutes les données",
  "confirm_clear": "Supprimer toutes vos données de progression ? Cette action est irréversible.",
  "email_section_title": "Envoyer ma progression par e-mail",
  "email_placeholder": "votre@email.com",
  "btn_send_report": "Envoyer le rapport",
  "email_hint": "Ouvre votre application de messagerie avec un résumé de progression pré-rempli. Vous pouvez le modifier avant l'envoi.",
  "report_header": "Stroke Sight – Entraîneur de champ visuel",
  "report_affected_side": "Côté atteint",
  "report_overview": "── APERÇU ──",
  "report_by_exercise": "── PAR EXERCICE ──",
  "report_total_sessions": "Séances totales",
  "report_minutes": "Minutes pratiquées",
  "report_avg_score": "Score moyen global",
  "report_avg_rt": "Temps de réaction moyen global",
  "report_improvement": "Amélioration (3 premières → 3 dernières) : score",
  "report_footer1": "Envoyé depuis Stroke Sight – Entraîneur de champ visuel",
  "report_footer2": "strokesight.app",
  "report_footer3": "Ces résultats sont destinés uniquement au suivi personnel. Stroke Sight est un outil de soutien au bien-être — pas un dispositif médical. Ces résultats ne constituent pas une évaluation clinique.",
  "no_sessions_report": "Terminez au moins une séance d'exercice d'abord.",
  "email_required": "Veuillez saisir une adresse e-mail.",
  "about_title": "À propos de Stroke Sight",
  "about_app_heading": "À propos de cette application",
  "about_app_body": "Stroke Sight est une application de soutien au bien-être pour les personnes vivant avec une hémianopsie — perte partielle de la vision souvent causée par un AVC. Ce n'est pas un dispositif médical et elle ne remplace pas la rééducation professionnelle. Utilisez-la en complément des conseils de votre neuro-ophtalmologiste ou de votre équipe de rééducation post-AVC.",
  "about_why_heading": "Pourquoi ces quatre exercices ?",
  "about_why_body": "Après un AVC causant une hémianopsie, le cerveau perd l'exploration automatique vers le champ atteint. Ces exercices sont fondés sur l'entraînement saccadique compensatoire — apprenant des mouvements oculaires délibérés pour compenser le champ absent.",
  "about_exercises_heading": "Les exercices",
  "about_how_heading": "Comment utiliser cette application",
  "about_how_1": "Visez 5 à 15 minutes par jour ; peu et souvent vaut mieux que des séances longues et irrégulières.",
  "about_how_2": "Commencez par Scintillement périphérique en cas de fatigue élevée.",
  "about_how_3": "Montrez l'onglet Progrès à votre thérapeute lors des consultations.",
  "about_how_4": "Cette application fonctionne entièrement hors ligne — aucune connexion internet requise après la première sauvegarde.",
  "about_important_heading": "Important",
  "about_important_body": "Cette application complète la rééducation professionnelle, elle ne la remplace pas. La récupération d'une perte de champ visuel liée à un AVC varie considérablement d'une personne à l'autre. Suivez toujours les recommandations de votre équipe clinique.",
  "btn_privacy": "Politique de confidentialité",
  "privacy_title": "Politique de confidentialité",
  "privacy_short_heading": "La version courte",
  "privacy_short_body": "Stroke Sight ne collecte aucune donnée personnelle. Tout ce que fait l'application se passe entièrement sur votre appareil. Pas de comptes, pas de suivi, pas d'analyses, pas d'internet nécessaire.",
  "lang_label": "Langue",
  "about_evidence_basis": "Les exercices pour hémianopsie (Anchor & Scan, Reading Line Scan, Peripheral Flicker, Visual Search Grid) sont fondés sur l'entraînement compensatoire à la balayage saccadique — approche soutenue par la recommandation NICE NG236 et plus de 40 ans de recherches de Zihl, Kerkhoff, Pambakian et Trauzettel-Klosinski. Les exercices pour la négligence spatiale unilatérale (Smooth Pursuit, calibration de Line Bisection) suivent la tradition d'entraînement de la poursuite lisse oculaire recommandée par les directives de la Société Neurologique Allemande et ayant reçu la note de preuve la plus élevée dans la revue systématique de Klinke et al. (2015). Les repères auditifs spatiaux s'appuient sur les recherches de stimulation multisensorielle de Bolognini et Tinelli. Les exercices pour scotome (Blind Spot Tracker, Gap Fill) offrent un entraînement de sensibilisation et une pratique de complétion perceptive autour de la tache aveugle. Cela complète — mais ne remplace pas — l'entraînement à la vision excentrique et au Locus Rétinien Préférentiel proposé par les spécialistes de basse vision.",
  "bisection_neglect_complete_left": "Séance terminée. Si vous avez eu tendance à appuyer à droite du centre, c'est le biais typique de la négligence. Votre conscience du côté gauche s'améliorera avec une pratique régulière.",
  "bisection_neglect_complete_right": "Séance terminée. Si vous avez eu tendance à appuyer à droite du centre, c'est le biais typique de la négligence. Votre conscience du côté droit s'améliorera avec une pratique régulière.",
  "cond_hemianopia": "Hémianopsie",
  "cond_hemianopia_desc": "Perte de la moitié de votre champ visuel",
  "cond_neglect": "Négligence Spatiale Unilatérale",
  "cond_neglect_desc": "Votre cerveau ne perçoit pas un côté",
  "cond_pick_quadrant": "Quel quadrant est affecté ?",
  "cond_pick_scotoma": "Appuyez sur votre zone approximative de tache aveugle",
  "cond_pick_side": "Quel côté est affecté ?",
  "cond_quadrantanopia": "Quadranopsie",
  "cond_quadrantanopia_desc": "Perte d'un quart de votre champ visuel",
  "cond_scotoma": "Scotome",
  "cond_scotoma_desc": "Une tache aveugle dans votre vision — entraînement de sensibilisation",
  "cond_title": "Quelle est votre condition visuelle ?",
  "ex_bisection_badge": "Calibrer",
  "ex_bisection_desc": "Bisectez des lignes pour mesurer votre biais spatial. Votre déviation calibre la difficulté de l'exercice de Balayage Attentionnel qui suit.",
  "ex_bisection_instr": "Appuyez là où vous pensez que se trouve le centre exact de chaque ligne. Votre déviation moyenne ajustera l'aide dont vous bénéficierez dans l'exercice suivant.",
  "ex_bisection_name": "Line Bisection",
  "ex_gapfill_badge": "Scotome",
  "ex_gapfill_desc": "Les cibles forment un motif avec des lacunes dans votre zone de tache aveugle. Appuyez là où les cibles manquantes devraient se trouver. Pratique de complétion perceptive — entraînant la capacité de votre cerveau à interpréter des informations visuelles incomplètes.",
  "ex_gapfill_instr": "Observez l'anneau de cibles. Certaines manquent car elles se trouvent dans votre tache aveugle. Appuyez là où vous pensez que les cibles manquantes devraient être.",
  "ex_gapfill_name": "Gap Fill",
  "ex_pursuit_badge": "Négligence",
  "ex_pursuit_desc": "Suivez une cible en mouvement tandis qu'elle se déplace vers votre côté négligé. Entraînement de la poursuite lisse oculaire — l'approche présentant les preuves les plus solides pour la récupération de la négligence spatiale unilatérale.",
  "ex_pursuit_instr": "Un cercle se déplace lentement sur l'écran vers votre côté négligé. Suivez-le des yeux. Lorsqu'il s'arrête, appuyez dessus pour confirmer que vous l'avez suivi.",
  "ex_pursuit_name": "Smooth Pursuit",
  "ex_tracker_badge": "Scotome",
  "ex_tracker_desc": "Suivez une cible en mouvement tandis qu'elle traverse votre zone de tache aveugle. Il s'agit d'un entraînement de sensibilisation — développant la capacité de votre cerveau à prédire et compenser autour du scotome, plutôt que la vision excentrique ou le développement du Locus Rétinien Préférentiel.",
  "ex_tracker_instr": "Regardez le point vert se déplacer sur l'écran. Lorsqu'il disparaît dans votre tache aveugle, appuyez là où vous pensez qu'il se trouve maintenant.",
  "ex_tracker_name": "Blind Spot Tracker",
  "progress_neglect_note": "Conseil de récupération de la négligence : demandez à quelqu'un d'observer de quel côté de l'écran vous avez tendance à manquer des cibles. L'amélioration se manifeste souvent par moins de cibles manquées de votre côté négligé après des semaines de pratique.",
  "pursuit_neglect_complete_left": "Séance terminée. Si certaines cibles de votre côté gauche étaient difficiles à remarquer, c'est normal dans la récupération de la négligence. Une pratique régulière aide.",
  "pursuit_neglect_complete_right": "Séance terminée. Si certaines cibles de votre côté droit étaient difficiles à remarquer, c'est normal dans la récupération de la négligence. Une pratique régulière aide.",
  "quad_LL": "Inférieur gauche",
  "quad_LR": "Inférieur droit",
  "quad_UL": "Supérieur gauche",
  "quad_UR": "Supérieur droit",
  "safety_warning": "Arrêtez et consultez votre médecin si vous ressentez une augmentation des maux de tête, des étourdissements, des nausées ou des symptômes visuels pendant ou après les exercices.",
  "settings_sound_hint": "Repères audio stéréo pendant les exercices. Subtil utilise des tonalités douces ; Proéminent utilise des tonalités plus fortes. Désactivez si les sons sont inconfortables ou désorientants.",
  "settings_sound_label": "Repères sonores",
  "settings_sound_off": "Désactivé",
  "settings_sound_prominent": "Proéminent",
  "settings_sound_subtle": "Subtil"
};

if (!window.WORD_LISTS) window.WORD_LISTS = {};
WORD_LISTS['fr'] = [
  "les",
  "des",
  "une",
  "qui",
  "par",
  "sur",
  "pas",
  "cas",
  "ces",
  "cet",
  "dix",
  "eau",
  "est",
  "été",
  "ici",
  "lui",
  "mal",
  "mer",
  "mot",
  "nez",
  "nul",
  "oui",
  "peu",
  "rue",
  "son",
  "sur",
  "tout",
  "bien",
  "bras",
  "beau",
  "coup",
  "dans",
  "dont",
  "doux",
  "droit",
  "faux",
  "fond",
  "fort",
  "gros",
  "haut",
  "jour",
  "juste",
  "loin",
  "long",
  "même",
  "mots",
  "neuf",
  "noir",
  "nord",
  "pain",
  "pied",
  "plan",
  "plein",
  "pont",
  "port",
  "raison",
  "rien",
  "soir",
  "temps",
  "vrai",
  "yeux"
];
