// Stroke Sight — Translations: ko
if (!window.STRINGS) window.STRINGS = {};
STRINGS['ko'] = {
  "tagline": "시야 훈련",
  "subtitle": "뇌졸중 후 반맹 회복을 위해 설계된 매일 운동. 짧은 세션, 꾸준한 연습.",
  "notice_title": "건강 지원 도구 — 의료 기기가 아닙니다.",
  "notice_body": "Stroke Sight는 전문적인 치료와 함께 일상적인 연습을 지원하도록 설계되었습니다. 어떤 의학적 상태도 진단, 치료 또는 치유하지 않습니다. 항상 신경 안과 전문의, 뇌졸중 재활팀 또는 기타 자격을 갖춘 임상 전문가의 지침을 따르십시오.",
  "side_question": "어느 쪽이 영향을 받았습니까?",
  "side_left": "왼쪽",
  "side_right": "오른쪽",
  "choose_exercise": "운동 선택",
  "nav_exercises": "운동",
  "nav_progress": "진행 상황",
  "nav_about": "앱 정보",
  "ex_anchor_name": "앵커 및 스캔",
  "ex_anchor_badge": "기초",
  "ex_reading_name": "읽기 라인 스캔",
  "ex_reading_badge": "읽기",
  "ex_flicker_name": "주변 플리커",
  "ex_flicker_badge": "인식",
  "ex_grid_name": "시각 탐색 그리드",
  "ex_grid_badge": "스캔",
  "ex_anchor_desc": "중앙 고정 십자를 바라봅니다. 눈을 빠르게 움직여 초록색 목표물을 탭합니다 — 70%는 맹점 훈련을 위해 영향받은 쪽에 나타납니다.",
  "ex_reading_desc": "앵커-스캔 읽기 습관을 재건합니다. 빨간 점에서 시작하여 굵은 목표 단어를 찾아 탭합니다.",
  "ex_flicker_desc": "중앙 십자에서 눈을 움직이지 않고 화면 어디서든 미묘한 노란 플리커를 감지합니다. 부담이 낮고 시각 인식 향상 효과가 높습니다.",
  "ex_grid_desc_ltr": "전체 그리드에 걸쳐 기호 사이에 숨겨진 목표 별을 찾습니다. 왼쪽에서 오른쪽으로, 행별로 스캔 — 실생활 스캔 작업을 시뮬레이션합니다.",
  "ex_grid_desc_rtl": "전체 그리드에 걸쳐 기호 사이에 숨겨진 목표 별을 찾습니다. 오른쪽에서 왼쪽으로, 행별로 스캔 — 실생활 스캔 작업을 시뮬레이션합니다.",
  "ex_anchor_instr": "초록색 점이 나타날 때까지 흰 십자에 시선을 고정하세요. 그런 다음 빠르게 시선을 이동하여 탭합니다. 점이 나타나기 전에 움직이지 마세요.",
  "ex_reading_instr_left": "먼저 왼쪽 가장자리의 빨간 앵커 점을 찾으세요. 그런 다음 오른쪽으로 스캔하여 굵은 흰 단어를 탭합니다. 읽기 스캔 패턴을 재훈련합니다.",
  "ex_reading_instr_right": "먼저 오른쪽 가장자리의 빨간 앵커 점을 찾으세요. 그런 다음 왼쪽으로 스캔하여 굵은 흰 단어를 탭합니다. 읽기 스캔 패턴을 재훈련합니다.",
  "ex_flicker_instr": "중앙 십자를 응시하세요 — 눈을 움직이지 마세요. 노란 플리커가 느껴지면 즉시 스페이스를 누르거나 화면을 탭합니다.",
  "ex_grid_instr_ltr": "기호 사이에 숨겨진 ★을 찾으세요. 왼쪽에서 오른쪽으로, 행별로 스캔합니다. 찾는 즉시 탭합니다.",
  "ex_grid_instr_rtl": "기호 사이에 숨겨진 ★을 찾으세요. 오른쪽에서 왼쪽으로, 행별로 스캔합니다. 찾는 즉시 탭합니다.",
  "start_prompt": "어디든 탭하여 시작",
  "session_complete": "세션 완료",
  "score_label": "점수",
  "hits_label": "성공",
  "accuracy_label": "정확도",
  "avg_reaction": "평균 반응",
  "btn_done": "완료",
  "time_label": "시간",
  "canvas_affected_left": "← 영향 시야",
  "canvas_sighted_right": "정상 시야 →",
  "canvas_sighted_left": "← 정상 시야",
  "canvas_affected_right": "영향 시야 →",
  "canvas_start_right": "여기서 시작 →",
  "canvas_start_left": "← 여기서 시작",
  "canvas_scan_right": "오른쪽 스캔 → 굵은 단어 탭",
  "canvas_scan_left": "굵은 단어 탭 ← 왼쪽 스캔",
  "canvas_reading_prompt_right": "빨간 앵커 점에서 시작, 오른쪽으로 스캔",
  "canvas_reading_prompt_left": "빨간 앵커 점에서 시작, 왼쪽으로 스캔",
  "canvas_grid_instr_ltr": "★ 찾기 — 왼쪽에서 오른쪽, 행별로",
  "canvas_grid_instr_rtl": "★ 찾기 — 오른쪽에서 왼쪽, 행별로",
  "canvas_grid_prompt_ltr": "그리드 왼쪽→오른쪽, 행별 스캔 — ★ 찾기",
  "canvas_grid_prompt_rtl": "그리드 오른쪽→왼쪽, 행별 스캔 — ★ 찾기",
  "progress_title": "나의 진행 상황",
  "total_sessions": "전체 세션",
  "minutes_practised": "연습 시간(분)",
  "avg_score": "평균 점수",
  "avg_reaction_time": "평균 반응",
  "recent_sessions": "최근 세션",
  "no_sessions_yet": "아직 세션이 없습니다. 운동을 완료하여 진행 상황을 추적하세요.",
  "sessions_count": "세션",
  "no_sessions_exercise": "이 운동의 세션이 아직 없습니다.",
  "bench_guide": "건강한 성인 기준 — 임상 목표가 아닙니다",
  "improvement_label": "처음 3회 → 마지막 3회",
  "score_up": "점수",
  "reaction_up": "반응",
  "best_score": "최고",
  "avg_score_short": "평균",
  "btn_clear_data": "모든 데이터 삭제",
  "confirm_clear": "모든 진행 데이터를 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.",
  "email_section_title": "진행 상황 이메일로 보내기",
  "email_placeholder": "your@email.com",
  "btn_send_report": "보고서 보내기",
  "email_hint": "진행 요약이 미리 작성된 메일 앱이 열립니다. 보내기 전에 편집할 수 있습니다.",
  "report_header": "Stroke Sight – 시야 트레이너",
  "report_affected_side": "영향받은 쪽",
  "report_overview": "── 개요 ──",
  "report_by_exercise": "── 운동별 ──",
  "report_total_sessions": "전체 세션",
  "report_minutes": "연습 시간(분)",
  "report_avg_score": "전체 평균 점수",
  "report_avg_rt": "전체 평균 반응 시간",
  "report_improvement": "개선(처음 3회 → 마지막 3회): 점수",
  "report_footer1": "Stroke Sight – 시야 트레이너에서 보냄",
  "report_footer2": "strokesight.app",
  "report_footer3": "이 결과는 개인 추적용입니다. Stroke Sight는 건강 지원 도구이며 의료 기기가 아닙니다. 결과는 임상 평가가 아닙니다.",
  "no_sessions_report": "먼저 하나 이상의 운동 세션을 완료하세요.",
  "email_required": "이메일 주소를 입력하세요.",
  "about_title": "Stroke Sight 정보",
  "about_app_heading": "이 앱에 대하여",
  "about_app_body": "Stroke Sight는 뇌졸중으로 인한 부분적인 시력 손실인 반맹을 가진 분들을 위한 건강 지원 앱입니다. 의료 기기가 아니며 전문적인 재활을 대체하지 않습니다. 신경 안과 전문의 또는 뇌졸중 재활팀의 지침과 함께 사용하세요.",
  "about_why_heading": "왜 이 네 가지 운동인가요?",
  "about_why_body": "반맹을 일으키는 뇌졸중 이후, 뇌는 영향받은 시야로의 자동 스캔 능력을 잃습니다. 이 운동들은 보상적 단속 운동 훈련에 기반하여 — 결손된 시야를 보완하기 위한 의도적인 안구 운동을 학습합니다.",
  "about_exercises_heading": "운동",
  "about_how_heading": "이 앱 사용 방법",
  "about_how_1": "하루 5~15분을 목표로 하세요. 드문 긴 세션보다 짧고 자주 하는 것이 더 효과적입니다.",
  "about_how_2": "피로가 심할 때는 주변 플리커부터 시작하세요.",
  "about_how_3": "진료 시 치료사에게 진행 탭을 보여주세요.",
  "about_how_4": "이 앱은 완전히 오프라인으로 작동합니다 — 첫 저장 후 인터넷이 필요 없습니다.",
  "about_important_heading": "중요",
  "about_important_body": "이 앱은 전문적인 재활의 보완이지 대체가 아닙니다. 뇌졸중 관련 시야 손실에서의 회복은 개인마다 크게 다릅니다. 항상 담당 임상팀의 지침을 따르세요.",
  "btn_privacy": "개인정보 처리방침",
  "privacy_title": "개인정보 처리방침",
  "privacy_short_heading": "요약",
  "privacy_short_body": "Stroke Sight는 어떠한 개인 데이터도 수집하지 않습니다. 앱의 모든 처리는 귀하의 기기에서만 이루어집니다. 계정 없음, 추적 없음, 분석 없음, 인터넷 불필요.",
  "lang_label": "언어",
  "about_evidence_basis": "반맹 운동(Anchor & Scan, Reading Line Scan, Peripheral Flicker, Visual Search Grid)은 보상적 사카드 스캐닝 훈련을 기반으로 하며, NICE NG236과 Zihl, Kerkhoff, Pambakian, Trauzettel-Klosinski의 40년 이상의 연구에 의해 지지됩니다. 편측 공간 무시 운동(Smooth Pursuit, Line Bisection 보정)은 독일 신경학회 지침이 권장하고 Klinke 등(2015) 체계적 리뷰에서 최고 근거 등급을 받은 원활추적 안구운동 훈련 전통을 따릅니다. 공간 청각 단서는 Bolognini와 Tinelli의 다감각 자극 연구를 기반으로 합니다. 암점 운동(Blind Spot Tracker, Gap Fill)은 맹점 영역 주변의 인식 훈련과 지각 완성 연습을 제공합니다. 이는 저시력 전문가가 제공하는 편심 시야 훈련 및 선호 망막 위치(PRL) 훈련을 보완하지만 대체하지는 않습니다.",
  "bisection_neglect_complete_left": "세션이 완료되었습니다. 중심보다 오른쪽을 탭하는 경향이 있었다면, 이는 전형적인 편측 무시 편향입니다. 꾸준한 연습으로 왼쪽 인식이 향상될 것입니다.",
  "bisection_neglect_complete_right": "세션이 완료되었습니다. 중심보다 오른쪽을 탭하는 경향이 있었다면, 이는 전형적인 편측 무시 편향입니다. 꾸준한 연습으로 오른쪽 인식이 향상될 것입니다.",
  "cond_hemianopia": "반맹",
  "cond_hemianopia_desc": "시야의 절반을 잃은 상태",
  "cond_neglect": "편측 공간 무시",
  "cond_neglect_desc": "뇌가 한쪽을 인식하지 못하는 상태",
  "cond_pick_quadrant": "어느 사분면이 영향을 받았습니까?",
  "cond_pick_scotoma": "대략적인 맹점 위치를 탭하세요",
  "cond_pick_side": "어느 쪽이 영향을 받았습니까?",
  "cond_quadrantanopia": "사분맹",
  "cond_quadrantanopia_desc": "시야의 4분의 1을 잃은 상태",
  "cond_scotoma": "암점",
  "cond_scotoma_desc": "시야 내 맹점 — 인식 훈련",
  "cond_title": "시각 상태를 선택하세요",
  "ex_bisection_badge": "보정",
  "ex_bisection_desc": "선분을 이등분하여 공간 편향을 측정합니다. 편차를 기반으로 이어지는 Attention Scan 운동의 난이도가 보정됩니다.",
  "ex_bisection_instr": "각 선분의 정확한 중심이라고 생각하는 곳을 탭하세요. 평균 편차가 다음 운동에서 제공받는 도움의 양을 조정합니다.",
  "ex_bisection_name": "Line Bisection",
  "ex_gapfill_badge": "암점",
  "ex_gapfill_desc": "표적이 맹점 영역에 빈틈이 있는 패턴을 형성합니다. 빠진 표적이 있어야 할 위치를 탭하세요. 불완전한 시각 정보를 뇌가 해석하는 능력을 훈련하는 지각 완성 연습입니다.",
  "ex_gapfill_instr": "표적 링을 보세요. 일부는 맹점에 해당하여 보이지 않습니다. 빠진 표적이 있다고 생각하는 위치를 탭하세요.",
  "ex_gapfill_name": "Gap Fill",
  "ex_pursuit_badge": "편측 공간 무시",
  "ex_pursuit_desc": "움직이는 표적이 무시 쪽으로 이동하는 것을 추적합니다. 원활추적 안구운동 훈련 — 편측 공간 무시 회복에 가장 강한 근거를 가진 접근법입니다.",
  "ex_pursuit_instr": "원이 천천히 화면을 가로질러 무시 쪽으로 이동합니다. 눈으로 따라가세요. 멈추면 추적했음을 확인하기 위해 탭하세요.",
  "ex_pursuit_name": "Smooth Pursuit",
  "ex_tracker_badge": "암점",
  "ex_tracker_desc": "움직이는 표적이 맹점 영역을 지나는 것을 추적합니다. 이것은 인식 훈련으로, 편심 시야나 PRL 발달이 아닌 암점 주변을 예측하고 보상하는 뇌의 능력을 키웁니다.",
  "ex_tracker_instr": "녹색 점이 화면을 가로질러 이동하는 것을 보세요. 맹점으로 사라지면 지금 어디에 있는지 생각되는 곳을 탭하세요.",
  "ex_tracker_name": "Blind Spot Tracker",
  "progress_neglect_note": "편측 공간 무시 회복 팁: 화면의 어느 쪽을 놓치는 경향이 있는지 주변 사람에게 관찰해 달라고 부탁하세요. 몇 주 연습 후 무시 쪽에서 놓치는 표적이 줄어드는 것으로 개선을 확인할 수 있습니다.",
  "pursuit_neglect_complete_left": "세션이 완료되었습니다. 왼쪽 일부 표적을 인식하기 어려웠다면, 편측 공간 무시 회복 과정에서 정상적인 현상입니다. 꾸준한 연습이 도움이 됩니다.",
  "pursuit_neglect_complete_right": "세션이 완료되었습니다. 오른쪽 일부 표적을 인식하기 어려웠다면, 편측 공간 무시 회복 과정에서 정상적인 현상입니다. 꾸준한 연습이 도움이 됩니다.",
  "quad_LL": "좌하",
  "quad_LR": "우하",
  "quad_UL": "좌상",
  "quad_UR": "우상",
  "safety_warning": "운동 중이나 후에 두통, 어지럼증, 구역질, 또는 시각 증상이 악화되면 즉시 중단하고 담당 의사와 상담하세요.",
  "settings_sound_hint": "운동 중 스테레오 오디오 단서입니다. 은은함은 부드러운 음, 두드러짐은 더 큰 음을 사용합니다. 소리가 불편하거나 혼란스러우면 끄세요.",
  "settings_sound_label": "음향 단서",
  "settings_sound_off": "끄기",
  "settings_sound_prominent": "두드러짐",
  "settings_sound_subtle": "은은함"
};

if (!window.WORD_LISTS) window.WORD_LISTS = {};
WORD_LISTS['ko'] = [
  "아침",
  "저녁",
  "하늘",
  "바다",
  "산",
  "강",
  "꽃",
  "나무",
  "강아지",
  "고양이",
  "물",
  "음식",
  "자동차",
  "기차",
  "집",
  "도시",
  "학교",
  "일",
  "책",
  "종이",
  "빨간",
  "하얀",
  "검은",
  "큰",
  "작은",
  "빠른",
  "느린",
  "새로운",
  "오래된",
  "높은",
  "사람",
  "아이",
  "어른",
  "친구",
  "가족",
  "아버지",
  "어머니",
  "여동생",
  "형",
  "언니",
  "먹다",
  "마시다",
  "보다",
  "듣다",
  "읽다",
  "쓰다",
  "걷다",
  "달리다",
  "자다",
  "일어나다",
  "오늘",
  "내일",
  "어제",
  "지금",
  "앞",
  "뒤",
  "오른쪽",
  "왼쪽",
  "안",
  "밖"
];
