// Stroke Sight — Translations: en
if (!window.STRINGS) window.STRINGS = {};
STRINGS['en'] = {
  "tagline": "Visual Field Training",
  "subtitle": "Evidence-based protocols suggest 15–30 minutes daily, at least 5 days per week, for 4–6 weeks. Two shorter sessions per day may be more effective than one longer session.",
  "notice_title": "Wellness support tool — not a medical device.",
  "notice_body": "Stroke Sight is designed to support your daily practice alongside professional care. It does not diagnose, treat, or cure any medical condition. Always follow the guidance of your neuro-optometrist, stroke rehabilitation team, or other qualified clinician.",
  "side_question": "Which side is affected?",
  "side_left": "Left side",
  "side_right": "Right side",
  "choose_exercise": "CHOOSE AN EXERCISE",
  "nav_exercises": "Exercises",
  "nav_progress": "Progress",
  "nav_about": "About",
  "ex_anchor_name": "Anchor & Scan",
  "ex_anchor_badge": "Foundation",
  "ex_reading_name": "Reading Line Scan",
  "ex_reading_badge": "Reading",
  "ex_flicker_name": "Peripheral Flicker",
  "ex_flicker_badge": "Awareness",
  "ex_grid_name": "Visual Search Grid",
  "ex_grid_badge": "Scanning",
  "ex_anchor_desc": "Hold the central fixation cross. Jump your eyes to tap green targets — 70% appear on your affected side to train saccades into the blind field.",
  "ex_reading_desc": "Rebuild the anchor-scanning reading habit. Start at the red dot, then scan to find and tap the bold target word.",
  "ex_flicker_desc": "Detect subtle yellow flickers anywhere on screen without moving your eyes from the central cross. Low demand, high awareness benefit.",
  "ex_grid_desc_ltr": "Find the target star hidden among symbols across a full grid. Scan left to right, row by row — simulates real-life scanning tasks.",
  "ex_grid_desc_rtl": "Find the target star hidden among symbols across a full grid. Scan right to left, row by row — simulates real-life scanning tasks.",
  "ex_anchor_instr": "Keep your eyes on the white cross until a green dot appears. Then quickly move your gaze and tap it. Do not move before the dot appears.",
  "ex_reading_instr_left": "Find the red anchor dot on the left edge first. Then scan right to tap the bold white word. Retrains the reading scan pattern.",
  "ex_reading_instr_right": "Find the red anchor dot on the right edge first. Then scan left to tap the bold white word. Retrains the reading scan pattern.",
  "ex_flicker_instr": "Stare at the central cross — do not move your eyes. When you sense any yellow flicker, press Space or tap anywhere immediately.",
  "ex_grid_instr_ltr": "Find the ★ star hidden among the symbols. Scan left to right, row by row. Tap it the moment you find it.",
  "ex_grid_instr_rtl": "Find the ★ star hidden among the symbols. Scan right to left, row by row. Tap it the moment you find it.",
  "start_prompt": "Tap anywhere to begin",
  "session_complete": "Session Complete",
  "score_label": "Score",
  "hits_label": "Hits",
  "accuracy_label": "Accuracy",
  "avg_reaction": "Avg reaction",
  "btn_done": "Done",
  "time_label": "Time",
  "canvas_affected_left": "← Affected field",
  "canvas_sighted_right": "Sighted field →",
  "canvas_sighted_left": "← Sighted field",
  "canvas_affected_right": "Affected field →",
  "canvas_start_right": "Start here →",
  "canvas_start_left": "← Start here",
  "canvas_scan_right": "Scan right → tap the bold white word",
  "canvas_scan_left": "Tap the bold white word ← scan left",
  "canvas_reading_prompt_right": "Start at the red anchor dot, then scan right for the bold word",
  "canvas_reading_prompt_left": "Start at the red anchor dot, then scan left for the bold word",
  "canvas_grid_instr_ltr": "Find the ★ star — scan left to right, row by row",
  "canvas_grid_instr_rtl": "Find the ★ star — scan right to left, row by row",
  "canvas_grid_prompt_ltr": "Scan the grid left to right, row by row — find the ★ star",
  "canvas_grid_prompt_rtl": "Scan the grid right to left, row by row — find the ★ star",
  "progress_title": "Your Progress",
  "total_sessions": "TOTAL SESSIONS",
  "minutes_practised": "MINUTES PRACTISED",
  "avg_score": "AVG SCORE",
  "avg_reaction_time": "AVG REACTION",
  "recent_sessions": "RECENT SESSIONS",
  "no_sessions_yet": "No sessions yet. Complete an exercise to track your progress here.",
  "sessions_count": "SESSIONS",
  "no_sessions_exercise": "No sessions yet for this exercise.",
  "bench_guide": "Typical healthy-adult guide — not a clinical target",
  "improvement_label": "First 3 → Last 3",
  "score_up": "score",
  "reaction_up": "reaction",
  "best_score": "Best",
  "avg_score_short": "Avg",
  "btn_clear_data": "Clear all data",
  "confirm_clear": "Delete all your progress data? This cannot be undone.",
  "email_section_title": "Email my progress",
  "email_placeholder": "your@email.com",
  "btn_send_report": "Send report",
  "email_hint": "Opens your mail app with a pre-filled progress summary. You can edit before sending.",
  "report_header": "Stroke Sight – Visual Field Trainer",
  "report_affected_side": "Affected side",
  "report_overview": "── OVERVIEW ──",
  "report_by_exercise": "── BY EXERCISE ──",
  "report_total_sessions": "Total sessions",
  "report_minutes": "Minutes practised",
  "report_avg_score": "Overall average score",
  "report_avg_rt": "Overall average reaction time",
  "report_improvement": "Improvement (first 3 → last 3): score",
  "report_footer1": "Sent from Stroke Sight – Visual Field Trainer",
  "report_footer2": "strokesight.app",
  "report_footer3": "These results are for personal tracking only. Stroke Sight is a wellness support tool — not a medical device. Results are not a clinical assessment.",
  "no_sessions_report": "Complete at least one exercise session first.",
  "email_required": "Please enter an email address.",
  "about_title": "About Stroke Sight",
  "about_app_heading": "About this app",
  "about_app_body": "for people living with post-stroke visual impairments — hemianopia, quadrantanopia, visual neglect, and scotoma. It is not a medical device and does not replace professional rehabilitation. Use it alongside guidance from your neuro-optometrist, stroke rehabilitation team, or low-vision specialist.",
  "about_why_heading": "Our approach to visual rehabilitation",
  "about_why_body": "After a stroke, different visual and attentional changes can occur depending on which part of the brain is affected. These exercises target the most common consequences — loss of part of the visual field, reduced awareness of one side of space, and blind spots within the remaining field — using approaches supported by clinical evidence.",
  "about_exercises_heading": "The exercises",
  "about_how_heading": "How to use this app",
  "about_how_1": "15–30 minutes daily, at least 5 days per week, for 4–6 weeks. Two shorter sessions may be more effective than one long one.",
  "safety_warning": "Stop and consult your clinician if you experience increased headaches, dizziness, nausea, or visual symptoms during or after exercises.",
  "about_how_2": "Start with Peripheral Flicker if fatigue is high.",
  "about_how_3": "Show your Progress tab to your therapist at appointments.",
  "about_how_4": "This app works fully offline — no internet needed after first save.",
  "about_important_heading": "Important",
  "about_important_body": "This app is a supplement to professional rehabilitation, not a replacement. Recovery from stroke-related visual field loss varies greatly between individuals. Always follow your clinical team's guidance.",
  "btn_privacy": "Privacy Policy",
  "privacy_title": "Privacy Policy",
  "privacy_short_heading": "The short version",
  "privacy_short_body": "Stroke Sight collects no personal data whatsoever. Everything the app does happens entirely on your device. No accounts, no tracking, no analytics, no internet required.",
  "lang_label": "Language",
  "cond_title": "What is your visual condition?",
  "cond_hemianopia": "Hemianopia",
  "cond_hemianopia_desc": "Loss of half your visual field",
  "cond_quadrantanopia": "Quadrantanopia",
  "cond_quadrantanopia_desc": "Loss of a quarter of your visual field",
  "cond_neglect": "Visual Neglect",
  "cond_neglect_desc": "Your brain doesn't notice one side",
  "cond_scotoma": "Scotoma",
  "cond_scotoma_desc": "A blind spot in your vision — awareness training",
  "cond_pick_side": "Which side is affected?",
  "cond_pick_quadrant": "Which quadrant is affected?",
  "cond_pick_scotoma": "Tap your approximate blind spot area",
  "quad_UL": "Upper left",
  "quad_UR": "Upper right",
  "quad_LL": "Lower left",
  "quad_LR": "Lower right",
  "ex_pursuit_name": "Smooth Pursuit",
  "ex_pursuit_badge": "Neglect",
  "ex_pursuit_desc": "Follow a moving target as it crosses toward your neglected side. Smooth pursuit eye movement training — the approach with the strongest evidence for visual neglect recovery.",
  "ex_pursuit_instr": "A circle moves slowly across the screen toward your neglected side. Follow it with your eyes. When it stops, tap it to confirm you tracked it.",
  "ex_bisection_name": "Line Bisection",
  "ex_bisection_badge": "Calibrate",
  "ex_bisection_desc": "Bisect lines to measure your spatial bias. Your deviation calibrates the difficulty of the Attention Scan exercise that follows.",
  "ex_bisection_instr": "Tap where you think the exact centre of each line is. Your average deviation will adjust how much help you get in the next exercise.",
  "ex_tracker_name": "Blind Spot Tracker",
  "ex_tracker_badge": "Scotoma",
  "ex_tracker_desc": "Track a moving target as it crosses your blind spot area. This is awareness training — building your brain's ability to predict and compensate around the scotoma, rather than eccentric viewing or PRL development.",
  "ex_tracker_instr": "Watch the green dot move across the screen. When it disappears into your blind spot, tap where you think it is right now.",
  "ex_gapfill_name": "Gap Fill",
  "ex_gapfill_badge": "Scotoma",
  "ex_gapfill_desc": "Targets form a pattern with gaps in your blind spot area. Tap where the missing targets should be. Perceptual completion practice — exercising your brain's ability to make sense of incomplete visual information.",
  "ex_gapfill_instr": "Look at the ring of targets. Some are missing because they fall in your blind spot. Tap where you think the missing ones should be.",
  "settings_sound_label": "Sound cues",
  "settings_sound_off": "Off",
  "settings_sound_subtle": "Subtle",
  "settings_sound_prominent": "Prominent",
  "settings_sound_hint": "Stereo audio cues during exercises. Subtle uses soft tones; Prominent uses louder tones. Turn off if sounds are uncomfortable or disorienting.",
  "about_evidence_basis": "Hemianopia exercises (Anchor & Scan, Reading Line Scan, Peripheral Flicker, Visual Search Grid) are based on compensatory saccadic scanning training — the approach supported by NICE NG236 and 40+ years of research from Zihl, Kerkhoff, Pambakian, and Trauzettel-Klosinski. Visual neglect exercises (Smooth Pursuit, Line Bisection calibration) follow the smooth pursuit eye movement training tradition recommended by the German Neurological Society guidelines and receiving the highest evidence grade in the Klinke et al. (2015) systematic review. Spatial auditory cues draw on the multisensory stimulation research of Bolognini and Tinelli. Scotoma exercises (Blind Spot Tracker, Gap Fill) provide awareness training and perceptual completion practice around the blind spot area. This complements — but does not replace — the eccentric viewing and Preferred Retinal Locus training offered by low-vision specialists.",
  "progress_neglect_note": "Neglect recovery tip: ask someone to watch which side of the screen you tend to miss. Improvement often shows as fewer missed targets on your neglected side over weeks of practice.",
  "pursuit_neglect_complete_left": "Session complete. If some targets on your left side were difficult to notice, that's normal in neglect recovery. Consistent practice helps.",
  "pursuit_neglect_complete_right": "Session complete. If some targets on your right side were difficult to notice, that's normal in neglect recovery. Consistent practice helps.",
  "bisection_neglect_complete_left": "Session complete. If you tended to tap to the right of centre, that's typical neglect bias. Your left-side awareness will improve with consistent practice.",
  "bisection_neglect_complete_right": "Session complete. If you tended to tap to the right of centre, that's typical neglect bias. Your right-side awareness will improve with consistent practice.",
  "upgrade_title": "You're ready for the next challenge",
  "upgrade_body": "You've made real progress across 3 levels. The full version includes 7 more levels of increasing challenge, continuing your rehabilitation as your skills develop — plus detailed progress exports to share with your therapist.",
  "upgrade_cta": "Get Full Version",
  "upgrade_dismiss": "Continue with free version"
};

if (!window.WORD_LISTS) window.WORD_LISTS = {};
WORD_LISTS['en'] = [
  "the",
  "and",
  "for",
  "are",
  "but",
  "not",
  "you",
  "all",
  "can",
  "her",
  "was",
  "one",
  "our",
  "out",
  "day",
  "get",
  "has",
  "him",
  "his",
  "how",
  "man",
  "new",
  "now",
  "old",
  "see",
  "two",
  "way",
  "who",
  "boy",
  "did",
  "its",
  "let",
  "put",
  "say",
  "she",
  "too",
  "use",
  "big",
  "hand",
  "home",
  "life",
  "keep",
  "last",
  "long",
  "made",
  "came",
  "each",
  "find",
  "good",
  "help",
  "left",
  "look",
  "move",
  "next",
  "open",
  "part",
  "some",
  "take",
  "that",
  "them",
  "then",
  "time",
  "turn",
  "very",
  "well",
  "with",
  "word",
  "work",
  "your"
];
