// Stroke Sight — Translations: ja
if (!window.STRINGS) window.STRINGS = {};
STRINGS['ja'] = {
  "tagline": "視野トレーニング",
  "subtitle": "脳卒中後の半盲回復のための毎日のエクササイズ。短いセッション、継続的な練習。",
  "notice_title": "健康支援ツール — 医療機器ではありません。",
  "notice_body": "Stroke Sightは、専門的なケアとともに日々の練習を支援するために設計されています。いかなる疾患の診断・治療・治癒も行いません。神経眼科医、脳卒中リハビリチーム、またはその他の資格を持つ医療専門家の指導に常に従ってください。",
  "side_question": "どちら側が影響を受けていますか？",
  "side_left": "左側",
  "side_right": "右側",
  "choose_exercise": "エクササイズを選択",
  "nav_exercises": "エクササイズ",
  "nav_progress": "進捗",
  "nav_about": "アプリについて",
  "ex_anchor_name": "アンカー＆スキャン",
  "ex_anchor_badge": "基礎",
  "ex_reading_name": "読書ラインスキャン",
  "ex_reading_badge": "読書",
  "ex_flicker_name": "周辺フリッカー",
  "ex_flicker_badge": "認識",
  "ex_grid_name": "視覚探索グリッド",
  "ex_grid_badge": "スキャン",
  "ex_anchor_desc": "中央の固視十字を見つめ続けてください。緑のターゲットをタップするために素早く目を動かします。70%は影響側に現れ、盲野へのサッケードを鍛えます。",
  "ex_reading_desc": "アンカー・スキャン読書習慣を再構築します。赤い点から始めて、太字のターゲット単語を探してタップします。",
  "ex_flicker_desc": "中央の十字から目を離さずに、画面上のどこかで微妙な黄色のフリッカーを感知します。負荷が低く、視覚認識の向上に効果的です。",
  "ex_grid_desc_ltr": "グリッド全体の記号の中に隠れたターゲット星を見つけます。左から右へ、行ごとにスキャン — 日常のスキャンタスクをシミュレートします。",
  "ex_grid_desc_rtl": "グリッド全体の記号の中に隠れたターゲット星を見つけます。右から左へ、行ごとにスキャン — 日常のスキャンタスクをシミュレートします。",
  "ex_anchor_instr": "緑の点が現れるまで白い十字に目を当ててください。次に素早く視線を移してタップします。点が現れる前に動かないでください。",
  "ex_reading_instr_left": "まず左端の赤いアンカー点を見つけます。次に右へスキャンして太字の白い単語をタップします。読書スキャンパターンを再訓練します。",
  "ex_reading_instr_right": "まず右端の赤いアンカー点を見つけます。次に左へスキャンして太字の白い単語をタップします。読書スキャンパターンを再訓練します。",
  "ex_flicker_instr": "中央の十字を見つめて — 目を動かさないでください。黄色いフリッカーを感じたら、すぐにスペースを押すか画面のどこかをタップします。",
  "ex_grid_instr_ltr": "記号の中に隠れた★を見つけます。左から右へ、行ごとにスキャンします。見つけた瞬間にタップします。",
  "ex_grid_instr_rtl": "記号の中に隠れた★を見つけます。右から左へ、行ごとにスキャンします。見つけた瞬間にタップします。",
  "start_prompt": "どこかをタップして開始",
  "session_complete": "セッション完了",
  "score_label": "スコア",
  "hits_label": "ヒット",
  "accuracy_label": "精度",
  "avg_reaction": "平均反応",
  "btn_done": "完了",
  "time_label": "時間",
  "canvas_affected_left": "← 影響側",
  "canvas_sighted_right": "正常側 →",
  "canvas_sighted_left": "← 正常側",
  "canvas_affected_right": "影響側 →",
  "canvas_start_right": "ここから →",
  "canvas_start_left": "← ここから",
  "canvas_scan_right": "右へスキャン → 太字をタップ",
  "canvas_scan_left": "太字をタップ ← 左へスキャン",
  "canvas_reading_prompt_right": "赤いアンカー点から始め、右へスキャン",
  "canvas_reading_prompt_left": "赤いアンカー点から始め、左へスキャン",
  "canvas_grid_instr_ltr": "★を探す — 左から右、行ごとに",
  "canvas_grid_instr_rtl": "★を探す — 右から左、行ごとに",
  "canvas_grid_prompt_ltr": "グリッドを左から右、行ごとにスキャン — ★を見つけて",
  "canvas_grid_prompt_rtl": "グリッドを右から左、行ごとにスキャン — ★を見つけて",
  "progress_title": "あなたの進捗",
  "total_sessions": "合計セッション",
  "minutes_practised": "練習時間（分）",
  "avg_score": "平均スコア",
  "avg_reaction_time": "平均反応",
  "recent_sessions": "最近のセッション",
  "no_sessions_yet": "まだセッションがありません。エクササイズを完了して進捗を記録しましょう。",
  "sessions_count": "セッション",
  "no_sessions_exercise": "このエクササイズのセッションはまだありません。",
  "bench_guide": "健康な成人の目安 — 臨床目標ではありません",
  "improvement_label": "最初の3回 → 最後の3回",
  "score_up": "スコア",
  "reaction_up": "反応",
  "best_score": "最高",
  "avg_score_short": "平均",
  "btn_clear_data": "全データを消去",
  "confirm_clear": "すべての進捗データを削除しますか？この操作は元に戻せません。",
  "email_section_title": "進捗をメールで送る",
  "email_placeholder": "your@email.com",
  "btn_send_report": "レポートを送信",
  "email_hint": "進捗サマリーが入力済みのメールアプリが開きます。送信前に編集できます。",
  "report_header": "Stroke Sight – 視野トレーナー",
  "report_affected_side": "影響側",
  "report_overview": "── 概要 ──",
  "report_by_exercise": "── エクササイズ別 ──",
  "report_total_sessions": "合計セッション",
  "report_minutes": "練習時間（分）",
  "report_avg_score": "全体平均スコア",
  "report_avg_rt": "全体平均反応時間",
  "report_improvement": "改善（最初の3回 → 最後の3回）：スコア",
  "report_footer1": "Stroke Sight – 視野トレーナーから送信",
  "report_footer2": "strokesight.app",
  "report_footer3": "これらの結果は個人的な記録用です。Stroke Sightは健康支援ツールであり、医療機器ではありません。結果は臨床評価ではありません。",
  "no_sessions_report": "まず少なくとも1回のエクササイズセッションを完了してください。",
  "email_required": "メールアドレスを入力してください。",
  "about_title": "Stroke Sightについて",
  "about_app_heading": "このアプリについて",
  "about_app_body": "Stroke Sightは、脳卒中などにより引き起こされる視野の部分的な喪失である半盲を抱えて生活する方々のための健康支援アプリです。医療機器ではなく、専門的なリハビリの代替にはなりません。神経眼科医や脳卒中リハビリチームの指導とともにご使用ください。",
  "about_why_heading": "なぜこの4つのエクササイズ？",
  "about_why_body": "脳卒中による半盲の後、脳は影響側への自動スキャンを失います。これらのエクササイズは補償的サッケードトレーニングに基づいており、欠損した視野を補うための意図的な眼球運動を学習します。",
  "about_exercises_heading": "エクササイズ",
  "about_how_heading": "このアプリの使い方",
  "about_how_1": "1日5〜15分を目標に。長い不定期セッションより、短くこまめな練習が効果的です。",
  "about_how_2": "疲労が強い場合は周辺フリッカーから始めてください。",
  "about_how_3": "診察時に進捗タブをセラピストに見せましょう。",
  "about_how_4": "このアプリは完全オフラインで動作します — 初回保存後はインターネット不要です。",
  "about_important_heading": "重要",
  "about_important_body": "このアプリは専門的なリハビリの補助であり、代替ではありません。脳卒中による視野障害からの回復は個人によって大きく異なります。常に担当医療チームの指導に従ってください。",
  "btn_privacy": "プライバシーポリシー",
  "privacy_title": "プライバシーポリシー",
  "privacy_short_heading": "概要",
  "privacy_short_body": "Stroke Sightは個人データを一切収集しません。アプリのすべての処理はお使いのデバイス上で完結します。アカウント不要、追跡なし、分析なし、インターネット不要。",
  "lang_label": "言語",
  "about_evidence_basis": "半盲エクササイズ（Anchor & Scan、Reading Line Scan、Peripheral Flicker、Visual Search Grid）は、代償的サッカード走査訓練に基づいており、NICE NG236および半盲・視野障害分野のZihl、Kerkhoff、Pambakian、Trauzettel-Klosinski各氏による40年以上の研究によって支持されています。半側空間無視エクササイズ（Smooth Pursuit、Line Bisection キャリブレーション）は、ドイツ神経学会ガイドラインが推奨し、Klinke ら（2015年）のシステマティックレビューで最高エビデンスグレードを獲得した追従性眼球運動訓練の流れを踏まえています。空間聴覚キューはBologniniおよびTinelliの多感覚刺激研究に基づいています。暗点エクササイズ（Blind Spot Tracker、Gap Fill）は盲点周辺の認識訓練と知覚補完練習を提供します。これはロービジョン専門家が行う偏心視訓練および選好網膜部位（PRL）訓練を補完するものであり、代替するものではありません。",
  "bisection_neglect_complete_left": "セッション完了です。中心より右側をタップする傾向があった場合、それは典型的な半側空間無視のバイアスです。継続的な練習により、左側への気づきが向上していきます。",
  "bisection_neglect_complete_right": "セッション完了です。中心より右側をタップする傾向があった場合、それは典型的な半側空間無視のバイアスです。継続的な練習により、右側への気づきが向上していきます。",
  "cond_hemianopia": "半盲",
  "cond_hemianopia_desc": "視野の半分を失った状態",
  "cond_neglect": "半側空間無視",
  "cond_neglect_desc": "脳が片側を認識しにくくなっている状態",
  "cond_pick_quadrant": "どの四分領域が影響を受けていますか？",
  "cond_pick_scotoma": "おおよその盲点の位置をタップしてください",
  "cond_pick_side": "どちら側が影響を受けていますか？",
  "cond_quadrantanopia": "四分盲",
  "cond_quadrantanopia_desc": "視野の四分の一を失った状態",
  "cond_scotoma": "暗点",
  "cond_scotoma_desc": "視野内の盲点 — 認識訓練",
  "cond_title": "あなたの視覚状態を教えてください",
  "ex_bisection_badge": "キャリブレーション",
  "ex_bisection_desc": "線分を二等分して空間バイアスを測定します。偏差によって、続くAttention Scanエクササイズの難易度がキャリブレーションされます。",
  "ex_bisection_instr": "各線分の正確な中心と思う位置をタップしてください。平均偏差に基づいて、次のエクササイズでのサポート量が調整されます。",
  "ex_bisection_name": "Line Bisection",
  "ex_gapfill_badge": "暗点",
  "ex_gapfill_desc": "ターゲットが盲点領域にギャップのあるパターンを形成します。欠けているターゲットがあるべき場所をタップしてください。不完全な視覚情報を脳が補完する能力を鍛える知覚補完練習です。",
  "ex_gapfill_instr": "ターゲットの輪を見てください。盲点に重なるため、いくつかが欠けています。欠けているターゲットがあると思う位置をタップしてください。",
  "ex_gapfill_name": "Gap Fill",
  "ex_pursuit_badge": "半側空間無視",
  "ex_pursuit_desc": "動くターゲットが無視側へ横断するのを追います。追従性眼球運動訓練 — 半側空間無視の回復に最も強いエビデンスを持つアプローチです。",
  "ex_pursuit_instr": "円がゆっくりと画面上を無視側へ向かって移動します。目で追いかけてください。止まったら、追跡できたことを確認するためタップしてください。",
  "ex_pursuit_name": "Smooth Pursuit",
  "ex_tracker_badge": "暗点",
  "ex_tracker_desc": "動くターゲットが盲点領域を横断するのを追います。これは認識訓練です — 偏心視やPRL発達ではなく、暗点周辺を予測・補正する脳の能力を高めます。",
  "ex_tracker_instr": "緑色のドットが画面を横切るのを見てください。盲点に消えたら、今どこにあるかと思う場所をタップしてください。",
  "ex_tracker_name": "Blind Spot Tracker",
  "progress_neglect_note": "半側空間無視の回復ヒント：画面のどちら側を見逃しがちかを誰かに観察してもらいましょう。数週間の練習を通じて、無視側で見逃すターゲットが減ることで改善が現れることが多いです。",
  "pursuit_neglect_complete_left": "セッション完了です。左側のターゲットに気づきにくいことがあった場合、それは半側空間無視の回復過程では正常です。継続的な練習が効果をもたらします。",
  "pursuit_neglect_complete_right": "セッション完了です。右側のターゲットに気づきにくいことがあった場合、それは半側空間無視の回復過程では正常です。継続的な練習が効果をもたらします。",
  "quad_LL": "左下",
  "quad_LR": "右下",
  "quad_UL": "左上",
  "quad_UR": "右上",
  "safety_warning": "エクササイズ中または後に頭痛・めまい・吐き気・視覚症状が悪化した場合は、直ちに中止し担当医師にご相談ください。",
  "settings_sound_hint": "エクササイズ中のステレオ音声キューです。「控えめ」は柔らかいトーン、「強調」は大きめのトーンを使用します。音が不快または不安定に感じる場合はオフにしてください。",
  "settings_sound_label": "音声キュー",
  "settings_sound_off": "オフ",
  "settings_sound_prominent": "強調",
  "settings_sound_subtle": "控えめ",
  "upgrade_title": "次のレベルに挑戦しましょう",
  "upgrade_body": "3つのレベルで確かな進歩を遂げました。フルバージョンには、さらに難度の高い７つのレベルが含まれており、スキルの向上に合わせてリハビリを続けられます — セラピストと共有できる詳細な進捗エクスポート機能付き。",
  "upgrade_cta": "フルバージョンを入手",
  "upgrade_dismiss": "無料版を続ける"
};

if (!window.WORD_LISTS) window.WORD_LISTS = {};
WORD_LISTS['ja'] = [
  "あさ",
  "よる",
  "そら",
  "うみ",
  "やま",
  "かわ",
  "はな",
  "き",
  "いぬ",
  "ねこ",
  "みず",
  "たべもの",
  "くるま",
  "でんしゃ",
  "いえ",
  "まち",
  "がっこう",
  "しごと",
  "ほん",
  "かみ",
  "あかい",
  "しろい",
  "くろい",
  "おおきい",
  "ちいさい",
  "はやい",
  "おそい",
  "あたらしい",
  "ふるい",
  "たかい",
  "ひと",
  "こども",
  "おとな",
  "ともだち",
  "かぞく",
  "おとうさん",
  "おかあさん",
  "いもうと",
  "あに",
  "ねえさん",
  "たべる",
  "のむ",
  "みる",
  "きく",
  "よむ",
  "かく",
  "あるく",
  "はしる",
  "ねる",
  "おきる",
  "きょう",
  "あした",
  "きのう",
  "いま",
  "まえ",
  "うしろ",
  "みぎ",
  "ひだり",
  "なか",
  "そと"
];
