// Stroke Sight — Translations: zh
if (!window.STRINGS) window.STRINGS = {};
STRINGS['zh'] = {
  "tagline": "视野训练",
  "subtitle": "专为中风后偏盲康复设计的每日练习。短时训练，坚持练习。",
  "notice_title": "健康辅助工具——非医疗器械。",
  "notice_body": "Stroke Sight 旨在配合专业医疗，支持您的日常练习。本应用不诊断、治疗或治愈任何疾病。请始终遵循神经视光师、中风康复团队或其他合格临床医生的指导。",
  "side_question": "哪侧受影响？",
  "side_left": "左侧",
  "side_right": "右侧",
  "choose_exercise": "选择练习",
  "nav_exercises": "练习",
  "nav_progress": "进度",
  "nav_about": "关于",
  "ex_anchor_name": "锚定与扫视",
  "ex_anchor_badge": "基础",
  "ex_reading_name": "阅读行扫视",
  "ex_reading_badge": "阅读",
  "ex_flicker_name": "周边闪烁",
  "ex_flicker_badge": "感知",
  "ex_grid_name": "视觉搜索网格",
  "ex_grid_badge": "扫描",
  "ex_anchor_desc": "保持注视中央固定十字。快速移动眼睛点击绿色目标——70% 出现在患侧，训练向盲区的扫视。",
  "ex_reading_desc": "重建锚定扫视阅读习惯。从红点出发，扫视找到并点击粗体目标词。",
  "ex_flicker_desc": "眼睛不离中央十字，感知屏幕任何位置的淡黄色闪烁。低负荷，高感知收益。",
  "ex_grid_desc_ltr": "在完整网格中找到隐藏于符号间的目标星号。从左到右逐行扫描——模拟日常扫视任务。",
  "ex_grid_desc_rtl": "在完整网格中找到隐藏于符号间的目标星号。从右到左逐行扫描——模拟日常扫视任务。",
  "ex_anchor_instr": "眼睛盯住白色十字，直到绿点出现。然后迅速移动视线并点击。绿点出现前不要移动。",
  "ex_reading_instr_left": "先找到左侧边缘的红色锚点。然后向右扫视点击粗体白色词语。重新训练阅读扫视模式。",
  "ex_reading_instr_right": "先找到右侧边缘的红色锚点。然后向左扫视点击粗体白色词语。重新训练阅读扫视模式。",
  "ex_flicker_instr": "凝视中央十字——眼睛不要移动。感知到任何黄色闪烁时，立即按空格键或点击屏幕。",
  "ex_grid_instr_ltr": "在符号中找到隐藏的 ★ 星号。从左到右逐行扫描。找到即点击。",
  "ex_grid_instr_rtl": "在符号中找到隐藏的 ★ 星号。从右到左逐行扫描。找到即点击。",
  "start_prompt": "点击任意处开始",
  "session_complete": "训练完成",
  "score_label": "得分",
  "hits_label": "命中",
  "accuracy_label": "准确率",
  "avg_reaction": "平均反应",
  "btn_done": "完成",
  "time_label": "时间",
  "canvas_affected_left": "← 患侧视野",
  "canvas_sighted_right": "正常视野 →",
  "canvas_sighted_left": "← 正常视野",
  "canvas_affected_right": "患侧视野 →",
  "canvas_start_right": "从这里开始 →",
  "canvas_start_left": "← 从这里开始",
  "canvas_scan_right": "向右扫视 → 点击粗体词",
  "canvas_scan_left": "点击粗体词 ← 向左扫视",
  "canvas_reading_prompt_right": "从红色锚点出发，向右扫视",
  "canvas_reading_prompt_left": "从红色锚点出发，向左扫视",
  "canvas_grid_instr_ltr": "找到 ★ 星号 — 从左到右，逐行扫描",
  "canvas_grid_instr_rtl": "找到 ★ 星号 — 从右到左，逐行扫描",
  "canvas_grid_prompt_ltr": "从左到右逐行扫描网格 — 找到 ★",
  "canvas_grid_prompt_rtl": "从右到左逐行扫描网格 — 找到 ★",
  "progress_title": "您的进度",
  "total_sessions": "总训练次数",
  "minutes_practised": "练习分钟数",
  "avg_score": "平均得分",
  "avg_reaction_time": "平均反应时间",
  "recent_sessions": "近期训练",
  "no_sessions_yet": "暂无训练记录。完成一项练习即可在此查看进度。",
  "sessions_count": "训练次数",
  "no_sessions_exercise": "此练习暂无训练记录。",
  "bench_guide": "健康成人参考值——非临床目标",
  "improvement_label": "前3次 → 后3次",
  "score_up": "得分",
  "reaction_up": "反应",
  "best_score": "最高",
  "avg_score_short": "平均",
  "btn_clear_data": "清除所有数据",
  "confirm_clear": "删除所有进度数据？此操作无法撤销。",
  "email_section_title": "通过邮件发送我的进度",
  "email_placeholder": "您的@邮箱.com",
  "btn_send_report": "发送报告",
  "email_hint": "打开邮件应用并预填写进度摘要。发送前可编辑修改。",
  "report_header": "Stroke Sight – 视野训练器",
  "report_affected_side": "患侧",
  "report_overview": "── 总览 ──",
  "report_by_exercise": "── 按练习 ──",
  "report_total_sessions": "总训练次数",
  "report_minutes": "练习分钟数",
  "report_avg_score": "总体平均得分",
  "report_avg_rt": "总体平均反应时间",
  "report_improvement": "进步（前3次 → 后3次）：得分",
  "report_footer1": "由 Stroke Sight – 视野训练器发送",
  "report_footer2": "strokesight.app",
  "report_footer3": "本结果仅供个人追踪使用。Stroke Sight 是健康辅助工具——非医疗器械。结果不构成临床评估。",
  "no_sessions_report": "请先完成至少一次训练。",
  "email_required": "请输入电子邮件地址。",
  "about_title": "关于 Stroke Sight",
  "about_app_heading": "关于本应用",
  "about_app_body": "Stroke Sight 是一款面向偏盲患者的健康辅助应用——偏盲是中风后常见的部分视力丧失。本应用非医疗器械，不替代专业康复治疗。请配合神经视光师或中风康复团队的指导使用。",
  "about_why_heading": "为什么是这四项练习？",
  "about_why_body": "中风导致偏盲后，大脑会失去向患侧视野的自动扫视能力。这些练习基于代偿性扫视训练——教导有意识的眼球运动，以弥补缺失的视野。",
  "about_exercises_heading": "练习项目",
  "about_how_heading": "如何使用本应用",
  "about_how_1": "每天练习 5–15 分钟；少量多次比长时间偶尔练习效果更好。",
  "about_how_2": "疲劳较重时，从周边闪烁练习开始。",
  "about_how_3": "复诊时将进度页面展示给治疗师。",
  "about_how_4": "本应用可完全离线使用——首次保存后无需联网。",
  "about_important_heading": "重要提示",
  "about_important_body": "本应用是专业康复的辅助，而非替代。中风相关视野损失的康复情况因人而异，差异显著。请始终遵循临床团队的指导。",
  "btn_privacy": "隐私政策",
  "privacy_title": "隐私政策",
  "privacy_short_heading": "简要说明",
  "privacy_short_body": "Stroke Sight 不收集任何个人数据。应用的所有操作均在您的设备本地完成。无账户、无追踪、无分析、无需联网。",
  "lang_label": "语言",
  "about_evidence_basis": "偏盲训练（Anchor & Scan、Reading Line Scan、Peripheral Flicker、Visual Search Grid）基于代偿性扫视扫描训练——该方法受到NICE NG236以及Zihl、Kerkhoff、Pambakian和Trauzettel-Klosinski逾40年研究的支持。单侧空间忽略训练（Smooth Pursuit、Line Bisection校准）遵循德国神经学会指南推荐、并在Klinke等人（2015年）系统评价中获得最高证据等级的平滑追踪眼动训练传统。空间听觉提示借鉴了Bolognini和Tinelli的多感官刺激研究。暗点训练（Blind Spot Tracker、Gap Fill）提供盲点区域周围的意识训练和感知补全练习。这是对低视力专科医生提供的偏心注视训练和首选视网膜位点（PRL）训练的补充，而非替代。",
  "bisection_neglect_complete_left": "本次训练已完成。如果您倾向于点击中心偏右的位置，这是典型的忽略偏向。坚持练习后，您对左侧的感知将会改善。",
  "bisection_neglect_complete_right": "本次训练已完成。如果您倾向于点击中心偏右的位置，这是典型的忽略偏向。坚持练习后，您对右侧的感知将会改善。",
  "cond_hemianopia": "偏盲",
  "cond_hemianopia_desc": "视野一半丧失",
  "cond_neglect": "单侧空间忽略",
  "cond_neglect_desc": "大脑忽略一侧空间",
  "cond_pick_quadrant": "哪个象限受到影响？",
  "cond_pick_scotoma": "请点击您大致的盲点区域",
  "cond_pick_side": "哪侧受到影响？",
  "cond_quadrantanopia": "象限盲",
  "cond_quadrantanopia_desc": "视野四分之一丧失",
  "cond_scotoma": "暗点",
  "cond_scotoma_desc": "视野中的盲点 — 意识训练",
  "cond_title": "您的视觉状况是什么？",
  "ex_bisection_badge": "校准",
  "ex_bisection_desc": "通过等分线段测量您的空间偏向。您的偏差将校准后续Attention Scan练习的难度。",
  "ex_bisection_instr": "点击您认为每条线段的正确中心位置。您的平均偏差将调整您在下一个练习中获得的辅助程度。",
  "ex_bisection_name": "Line Bisection",
  "ex_gapfill_badge": "暗点",
  "ex_gapfill_desc": "目标在您的盲点区域形成带有缺口的图案。请点击缺失目标应该在的位置。感知补全练习 — 训练大脑理解不完整视觉信息的能力。",
  "ex_gapfill_instr": "观察目标环。由于部分目标落在您的盲点中，它们缺失了。请点击您认为缺失目标应在的位置。",
  "ex_gapfill_name": "Gap Fill",
  "ex_pursuit_badge": "单侧空间忽略",
  "ex_pursuit_desc": "跟随一个向您忽略侧移动的目标。平滑追踪眼动训练 — 在单侧空间忽略康复中具有最强证据的方法。",
  "ex_pursuit_instr": "一个圆圈缓慢地向您的忽略侧横穿屏幕。用眼睛跟随它。当它停止时，点击以确认您已追踪到它。",
  "ex_pursuit_name": "Smooth Pursuit",
  "ex_tracker_badge": "暗点",
  "ex_tracker_desc": "追踪一个穿越您盲点区域的移动目标。这是意识训练 — 培养大脑在暗点周围进行预测和补偿的能力，而非偏心注视或PRL发展训练。",
  "ex_tracker_instr": "观察绿点横穿屏幕。当它消失进入您的盲点时，点击您认为它现在所在的位置。",
  "ex_tracker_name": "Blind Spot Tracker",
  "progress_neglect_note": "单侧空间忽略康复提示：请他人观察您倾向于错过屏幕的哪一侧。经过数周练习，忽略侧遗漏目标减少通常是改善的标志。",
  "pursuit_neglect_complete_left": "本次训练已完成。如果左侧某些目标难以察觉，这在单侧空间忽略康复过程中是正常的。坚持练习会有帮助。",
  "pursuit_neglect_complete_right": "本次训练已完成。如果右侧某些目标难以察觉，这在单侧空间忽略康复过程中是正常的。坚持练习会有帮助。",
  "quad_LL": "左下",
  "quad_LR": "右下",
  "quad_UL": "左上",
  "quad_UR": "右上",
  "safety_warning": "若在练习期间或之后出现头痛加剧、头晕、恶心或视觉症状，请立即停止并咨询您的临床医生。",
  "settings_sound_hint": "练习期间的立体声音频提示。柔和模式使用轻柔音调；突出模式使用较响音调。如果声音令您感到不适或迷失方向，请关闭。",
  "settings_sound_label": "声音提示",
  "settings_sound_off": "关闭",
  "settings_sound_prominent": "突出",
  "settings_sound_subtle": "柔和",
  "upgrade_title": "您已准备好迎接下一个挑战",
  "upgrade_body": "您已在３个级别中取得了实质性进展。完整版包含另外７个难度递增的级别，随着您技能的提升继续您的康复训练——还包含详细的进度导出功能，可与您的治疗师分享。",
  "upgrade_cta": "获取完整版",
  "upgrade_dismiss": "继续使用免费版"
};

if (!window.WORD_LISTS) window.WORD_LISTS = {};
WORD_LISTS['zh'] = [
  "家",
  "天",
  "夜",
  "水",
  "饭",
  "工作",
  "手",
  "眼",
  "心",
  "时间",
  "话",
  "路",
  "名",
  "人",
  "国",
  "城",
  "门",
  "书",
  "歌",
  "孩子",
  "妈",
  "爸",
  "哥",
  "姐",
  "朋友",
  "学校",
  "市场",
  "房间",
  "窗",
  "树",
  "花",
  "果",
  "奶",
  "面包",
  "茶",
  "河",
  "火",
  "风",
  "天空",
  "地",
  "脚",
  "嘴",
  "耳",
  "鼻",
  "头",
  "叶",
  "牛",
  "狗",
  "鱼",
  "鸟",
  "色",
  "蓝",
  "红",
  "绿",
  "白",
  "黑",
  "大",
  "小",
  "新",
  "旧"
];
